/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehicleStorageRouteImport } from './routes/vehicle-storage'
import { Route as VehicleRecoveryRouteImport } from './routes/vehicle-recovery'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MobileTyreServiceRouteImport } from './routes/mobile-tyre-service'
import { Route as JumpStartRouteImport } from './routes/jump-start'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BatteryReplacementRouteImport } from './routes/battery-replacement'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VehicleStorageRoute = VehicleStorageRouteImport.update({
  id: '/vehicle-storage',
  path: '/vehicle-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleRecoveryRoute = VehicleRecoveryRouteImport.update({
  id: '/vehicle-recovery',
  path: '/vehicle-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileTyreServiceRoute = MobileTyreServiceRouteImport.update({
  id: '/mobile-tyre-service',
  path: '/mobile-tyre-service',
  getParentRoute: () => rootRouteImport,
} as any)
const JumpStartRoute = JumpStartRouteImport.update({
  id: '/jump-start',
  path: '/jump-start',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteryReplacementRoute = BatteryReplacementRouteImport.update({
  id: '/battery-replacement',
  path: '/battery-replacement',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/battery-replacement': typeof BatteryReplacementRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/jump-start': typeof JumpStartRoute
  '/mobile-tyre-service': typeof MobileTyreServiceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vehicle-recovery': typeof VehicleRecoveryRoute
  '/vehicle-storage': typeof VehicleStorageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/battery-replacement': typeof BatteryReplacementRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/jump-start': typeof JumpStartRoute
  '/mobile-tyre-service': typeof MobileTyreServiceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vehicle-recovery': typeof VehicleRecoveryRoute
  '/vehicle-storage': typeof VehicleStorageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/battery-replacement': typeof BatteryReplacementRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/jump-start': typeof JumpStartRoute
  '/mobile-tyre-service': typeof MobileTyreServiceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vehicle-recovery': typeof VehicleRecoveryRoute
  '/vehicle-storage': typeof VehicleStorageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/battery-replacement'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/jump-start'
    | '/mobile-tyre-service'
    | '/privacy-policy'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/vehicle-recovery'
    | '/vehicle-storage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/battery-replacement'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/jump-start'
    | '/mobile-tyre-service'
    | '/privacy-policy'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/vehicle-recovery'
    | '/vehicle-storage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/battery-replacement'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/jump-start'
    | '/mobile-tyre-service'
    | '/privacy-policy'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/vehicle-recovery'
    | '/vehicle-storage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BatteryReplacementRoute: typeof BatteryReplacementRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  JumpStartRoute: typeof JumpStartRoute
  MobileTyreServiceRoute: typeof MobileTyreServiceRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VehicleRecoveryRoute: typeof VehicleRecoveryRoute
  VehicleStorageRoute: typeof VehicleStorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicle-storage': {
      id: '/vehicle-storage'
      path: '/vehicle-storage'
      fullPath: '/vehicle-storage'
      preLoaderRoute: typeof VehicleStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-recovery': {
      id: '/vehicle-recovery'
      path: '/vehicle-recovery'
      fullPath: '/vehicle-recovery'
      preLoaderRoute: typeof VehicleRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-tyre-service': {
      id: '/mobile-tyre-service'
      path: '/mobile-tyre-service'
      fullPath: '/mobile-tyre-service'
      preLoaderRoute: typeof MobileTyreServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jump-start': {
      id: '/jump-start'
      path: '/jump-start'
      fullPath: '/jump-start'
      preLoaderRoute: typeof JumpStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battery-replacement': {
      id: '/battery-replacement'
      path: '/battery-replacement'
      fullPath: '/battery-replacement'
      preLoaderRoute: typeof BatteryReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BatteryReplacementRoute: BatteryReplacementRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  JumpStartRoute: JumpStartRoute,
  MobileTyreServiceRoute: MobileTyreServiceRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VehicleRecoveryRoute: VehicleRecoveryRoute,
  VehicleStorageRoute: VehicleStorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
