/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccidentRecoveryRouteImport } from './routes/accident-recovery'
import { Route as AuctionVehicleCollectionRouteImport } from './routes/auction-vehicle-collection'
import { Route as BreakdownRecoveryRouteImport } from './routes/breakdown-recovery'
import { Route as CarRecoveryRouteImport } from './routes/car-recovery'
import { Route as CarTrailerRecoveryRouteImport } from './routes/car-trailer-recovery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmergencyCarRecoveryRouteImport } from './routes/emergency-car-recovery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FlatBatteryAssistanceRouteImport } from './routes/flat-battery-assistance'
import { Route as FuelDeliveryRouteImport } from './routes/fuel-delivery'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JumpStartRouteImport } from './routes/jump-start'
import { Route as LongDistanceVehicleTransportRouteImport } from './routes/long-distance-vehicle-transport'
import { Route as LuxuryExoticCarTowingRouteImport } from './routes/luxury-exotic-car-towing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RecoveryToMechanicRouteImport } from './routes/recovery-to-mechanic'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Suv4x4RecoveryRouteImport } from './routes/suv-4x4-recovery'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TradeVehicleDeliveryRouteImport } from './routes/trade-vehicle-delivery'
import { Route as TrailerTransportRouteImport } from './routes/trailer-transport'
import { Route as VanRecoveryRouteImport } from './routes/van-recovery'
import { Route as VehicleTransportRouteImport } from './routes/vehicle-transport'
import { Route as VehicleWinchingRouteImport } from './routes/vehicle-winching'
import { Route as WrongFuelRecoveryRouteImport } from './routes/wrong-fuel-recovery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccidentRecoveryRoute = AccidentRecoveryRouteImport.update({
  id: '/accident-recovery',
  path: '/accident-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionVehicleCollectionRoute =
  AuctionVehicleCollectionRouteImport.update({
    id: '/auction-vehicle-collection',
    path: '/auction-vehicle-collection',
    getParentRoute: () => rootRouteImport,
  } as any)
const BreakdownRecoveryRoute = BreakdownRecoveryRouteImport.update({
  id: '/breakdown-recovery',
  path: '/breakdown-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CarRecoveryRoute = CarRecoveryRouteImport.update({
  id: '/car-recovery',
  path: '/car-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CarTrailerRecoveryRoute = CarTrailerRecoveryRouteImport.update({
  id: '/car-trailer-recovery',
  path: '/car-trailer-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyCarRecoveryRoute = EmergencyCarRecoveryRouteImport.update({
  id: '/emergency-car-recovery',
  path: '/emergency-car-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatBatteryAssistanceRoute = FlatBatteryAssistanceRouteImport.update({
  id: '/flat-battery-assistance',
  path: '/flat-battery-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelDeliveryRoute = FuelDeliveryRouteImport.update({
  id: '/fuel-delivery',
  path: '/fuel-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JumpStartRoute = JumpStartRouteImport.update({
  id: '/jump-start',
  path: '/jump-start',
  getParentRoute: () => rootRouteImport,
} as any)
const LongDistanceVehicleTransportRoute =
  LongDistanceVehicleTransportRouteImport.update({
    id: '/long-distance-vehicle-transport',
    path: '/long-distance-vehicle-transport',
    getParentRoute: () => rootRouteImport,
  } as any)
const LuxuryExoticCarTowingRoute = LuxuryExoticCarTowingRouteImport.update({
  id: '/luxury-exotic-car-towing',
  path: '/luxury-exotic-car-towing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryToMechanicRoute = RecoveryToMechanicRouteImport.update({
  id: '/recovery-to-mechanic',
  path: '/recovery-to-mechanic',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Suv4x4RecoveryRoute = Suv4x4RecoveryRouteImport.update({
  id: '/suv-4x4-recovery',
  path: '/suv-4x4-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeVehicleDeliveryRoute = TradeVehicleDeliveryRouteImport.update({
  id: '/trade-vehicle-delivery',
  path: '/trade-vehicle-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailerTransportRoute = TrailerTransportRouteImport.update({
  id: '/trailer-transport',
  path: '/trailer-transport',
  getParentRoute: () => rootRouteImport,
} as any)
const VanRecoveryRoute = VanRecoveryRouteImport.update({
  id: '/van-recovery',
  path: '/van-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleTransportRoute = VehicleTransportRouteImport.update({
  id: '/vehicle-transport',
  path: '/vehicle-transport',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleWinchingRoute = VehicleWinchingRouteImport.update({
  id: '/vehicle-winching',
  path: '/vehicle-winching',
  getParentRoute: () => rootRouteImport,
} as any)
const WrongFuelRecoveryRoute = WrongFuelRecoveryRouteImport.update({
  id: '/wrong-fuel-recovery',
  path: '/wrong-fuel-recovery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accident-recovery': typeof AccidentRecoveryRoute
  '/auction-vehicle-collection': typeof AuctionVehicleCollectionRoute
  '/breakdown-recovery': typeof BreakdownRecoveryRoute
  '/car-recovery': typeof CarRecoveryRoute
  '/car-trailer-recovery': typeof CarTrailerRecoveryRoute
  '/contact': typeof ContactRoute
  '/emergency-car-recovery': typeof EmergencyCarRecoveryRoute
  '/faqs': typeof FaqsRoute
  '/flat-battery-assistance': typeof FlatBatteryAssistanceRoute
  '/fuel-delivery': typeof FuelDeliveryRoute
  '/gallery': typeof GalleryRoute
  '/jump-start': typeof JumpStartRoute
  '/long-distance-vehicle-transport': typeof LongDistanceVehicleTransportRoute
  '/luxury-exotic-car-towing': typeof LuxuryExoticCarTowingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recovery-to-mechanic': typeof RecoveryToMechanicRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suv-4x4-recovery': typeof Suv4x4RecoveryRoute
  '/terms': typeof TermsRoute
  '/trade-vehicle-delivery': typeof TradeVehicleDeliveryRoute
  '/trailer-transport': typeof TrailerTransportRoute
  '/van-recovery': typeof VanRecoveryRoute
  '/vehicle-transport': typeof VehicleTransportRoute
  '/vehicle-winching': typeof VehicleWinchingRoute
  '/wrong-fuel-recovery': typeof WrongFuelRecoveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accident-recovery': typeof AccidentRecoveryRoute
  '/auction-vehicle-collection': typeof AuctionVehicleCollectionRoute
  '/breakdown-recovery': typeof BreakdownRecoveryRoute
  '/car-recovery': typeof CarRecoveryRoute
  '/car-trailer-recovery': typeof CarTrailerRecoveryRoute
  '/contact': typeof ContactRoute
  '/emergency-car-recovery': typeof EmergencyCarRecoveryRoute
  '/faqs': typeof FaqsRoute
  '/flat-battery-assistance': typeof FlatBatteryAssistanceRoute
  '/fuel-delivery': typeof FuelDeliveryRoute
  '/gallery': typeof GalleryRoute
  '/jump-start': typeof JumpStartRoute
  '/long-distance-vehicle-transport': typeof LongDistanceVehicleTransportRoute
  '/luxury-exotic-car-towing': typeof LuxuryExoticCarTowingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recovery-to-mechanic': typeof RecoveryToMechanicRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suv-4x4-recovery': typeof Suv4x4RecoveryRoute
  '/terms': typeof TermsRoute
  '/trade-vehicle-delivery': typeof TradeVehicleDeliveryRoute
  '/trailer-transport': typeof TrailerTransportRoute
  '/van-recovery': typeof VanRecoveryRoute
  '/vehicle-transport': typeof VehicleTransportRoute
  '/vehicle-winching': typeof VehicleWinchingRoute
  '/wrong-fuel-recovery': typeof WrongFuelRecoveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accident-recovery': typeof AccidentRecoveryRoute
  '/auction-vehicle-collection': typeof AuctionVehicleCollectionRoute
  '/breakdown-recovery': typeof BreakdownRecoveryRoute
  '/car-recovery': typeof CarRecoveryRoute
  '/car-trailer-recovery': typeof CarTrailerRecoveryRoute
  '/contact': typeof ContactRoute
  '/emergency-car-recovery': typeof EmergencyCarRecoveryRoute
  '/faqs': typeof FaqsRoute
  '/flat-battery-assistance': typeof FlatBatteryAssistanceRoute
  '/fuel-delivery': typeof FuelDeliveryRoute
  '/gallery': typeof GalleryRoute
  '/jump-start': typeof JumpStartRoute
  '/long-distance-vehicle-transport': typeof LongDistanceVehicleTransportRoute
  '/luxury-exotic-car-towing': typeof LuxuryExoticCarTowingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recovery-to-mechanic': typeof RecoveryToMechanicRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suv-4x4-recovery': typeof Suv4x4RecoveryRoute
  '/terms': typeof TermsRoute
  '/trade-vehicle-delivery': typeof TradeVehicleDeliveryRoute
  '/trailer-transport': typeof TrailerTransportRoute
  '/van-recovery': typeof VanRecoveryRoute
  '/vehicle-transport': typeof VehicleTransportRoute
  '/vehicle-winching': typeof VehicleWinchingRoute
  '/wrong-fuel-recovery': typeof WrongFuelRecoveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accident-recovery'
    | '/auction-vehicle-collection'
    | '/breakdown-recovery'
    | '/car-recovery'
    | '/car-trailer-recovery'
    | '/contact'
    | '/emergency-car-recovery'
    | '/faqs'
    | '/flat-battery-assistance'
    | '/fuel-delivery'
    | '/gallery'
    | '/jump-start'
    | '/long-distance-vehicle-transport'
    | '/luxury-exotic-car-towing'
    | '/privacy-policy'
    | '/recovery-to-mechanic'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/suv-4x4-recovery'
    | '/terms'
    | '/trade-vehicle-delivery'
    | '/trailer-transport'
    | '/van-recovery'
    | '/vehicle-transport'
    | '/vehicle-winching'
    | '/wrong-fuel-recovery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accident-recovery'
    | '/auction-vehicle-collection'
    | '/breakdown-recovery'
    | '/car-recovery'
    | '/car-trailer-recovery'
    | '/contact'
    | '/emergency-car-recovery'
    | '/faqs'
    | '/flat-battery-assistance'
    | '/fuel-delivery'
    | '/gallery'
    | '/jump-start'
    | '/long-distance-vehicle-transport'
    | '/luxury-exotic-car-towing'
    | '/privacy-policy'
    | '/recovery-to-mechanic'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/suv-4x4-recovery'
    | '/terms'
    | '/trade-vehicle-delivery'
    | '/trailer-transport'
    | '/van-recovery'
    | '/vehicle-transport'
    | '/vehicle-winching'
    | '/wrong-fuel-recovery'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accident-recovery'
    | '/auction-vehicle-collection'
    | '/breakdown-recovery'
    | '/car-recovery'
    | '/car-trailer-recovery'
    | '/contact'
    | '/emergency-car-recovery'
    | '/faqs'
    | '/flat-battery-assistance'
    | '/fuel-delivery'
    | '/gallery'
    | '/jump-start'
    | '/long-distance-vehicle-transport'
    | '/luxury-exotic-car-towing'
    | '/privacy-policy'
    | '/recovery-to-mechanic'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/suv-4x4-recovery'
    | '/terms'
    | '/trade-vehicle-delivery'
    | '/trailer-transport'
    | '/van-recovery'
    | '/vehicle-transport'
    | '/vehicle-winching'
    | '/wrong-fuel-recovery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccidentRecoveryRoute: typeof AccidentRecoveryRoute
  AuctionVehicleCollectionRoute: typeof AuctionVehicleCollectionRoute
  BreakdownRecoveryRoute: typeof BreakdownRecoveryRoute
  CarRecoveryRoute: typeof CarRecoveryRoute
  CarTrailerRecoveryRoute: typeof CarTrailerRecoveryRoute
  ContactRoute: typeof ContactRoute
  EmergencyCarRecoveryRoute: typeof EmergencyCarRecoveryRoute
  FaqsRoute: typeof FaqsRoute
  FlatBatteryAssistanceRoute: typeof FlatBatteryAssistanceRoute
  FuelDeliveryRoute: typeof FuelDeliveryRoute
  GalleryRoute: typeof GalleryRoute
  JumpStartRoute: typeof JumpStartRoute
  LongDistanceVehicleTransportRoute: typeof LongDistanceVehicleTransportRoute
  LuxuryExoticCarTowingRoute: typeof LuxuryExoticCarTowingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RecoveryToMechanicRoute: typeof RecoveryToMechanicRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Suv4x4RecoveryRoute: typeof Suv4x4RecoveryRoute
  TermsRoute: typeof TermsRoute
  TradeVehicleDeliveryRoute: typeof TradeVehicleDeliveryRoute
  TrailerTransportRoute: typeof TrailerTransportRoute
  VanRecoveryRoute: typeof VanRecoveryRoute
  VehicleTransportRoute: typeof VehicleTransportRoute
  VehicleWinchingRoute: typeof VehicleWinchingRoute
  WrongFuelRecoveryRoute: typeof WrongFuelRecoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accident-recovery': {
      id: '/accident-recovery'
      path: '/accident-recovery'
      fullPath: '/accident-recovery'
      preLoaderRoute: typeof AccidentRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction-vehicle-collection': {
      id: '/auction-vehicle-collection'
      path: '/auction-vehicle-collection'
      fullPath: '/auction-vehicle-collection'
      preLoaderRoute: typeof AuctionVehicleCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breakdown-recovery': {
      id: '/breakdown-recovery'
      path: '/breakdown-recovery'
      fullPath: '/breakdown-recovery'
      preLoaderRoute: typeof BreakdownRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-recovery': {
      id: '/car-recovery'
      path: '/car-recovery'
      fullPath: '/car-recovery'
      preLoaderRoute: typeof CarRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-trailer-recovery': {
      id: '/car-trailer-recovery'
      path: '/car-trailer-recovery'
      fullPath: '/car-trailer-recovery'
      preLoaderRoute: typeof CarTrailerRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-car-recovery': {
      id: '/emergency-car-recovery'
      path: '/emergency-car-recovery'
      fullPath: '/emergency-car-recovery'
      preLoaderRoute: typeof EmergencyCarRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flat-battery-assistance': {
      id: '/flat-battery-assistance'
      path: '/flat-battery-assistance'
      fullPath: '/flat-battery-assistance'
      preLoaderRoute: typeof FlatBatteryAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel-delivery': {
      id: '/fuel-delivery'
      path: '/fuel-delivery'
      fullPath: '/fuel-delivery'
      preLoaderRoute: typeof FuelDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jump-start': {
      id: '/jump-start'
      path: '/jump-start'
      fullPath: '/jump-start'
      preLoaderRoute: typeof JumpStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/long-distance-vehicle-transport': {
      id: '/long-distance-vehicle-transport'
      path: '/long-distance-vehicle-transport'
      fullPath: '/long-distance-vehicle-transport'
      preLoaderRoute: typeof LongDistanceVehicleTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-exotic-car-towing': {
      id: '/luxury-exotic-car-towing'
      path: '/luxury-exotic-car-towing'
      fullPath: '/luxury-exotic-car-towing'
      preLoaderRoute: typeof LuxuryExoticCarTowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-to-mechanic': {
      id: '/recovery-to-mechanic'
      path: '/recovery-to-mechanic'
      fullPath: '/recovery-to-mechanic'
      preLoaderRoute: typeof RecoveryToMechanicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suv-4x4-recovery': {
      id: '/suv-4x4-recovery'
      path: '/suv-4x4-recovery'
      fullPath: '/suv-4x4-recovery'
      preLoaderRoute: typeof Suv4x4RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-vehicle-delivery': {
      id: '/trade-vehicle-delivery'
      path: '/trade-vehicle-delivery'
      fullPath: '/trade-vehicle-delivery'
      preLoaderRoute: typeof TradeVehicleDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trailer-transport': {
      id: '/trailer-transport'
      path: '/trailer-transport'
      fullPath: '/trailer-transport'
      preLoaderRoute: typeof TrailerTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/van-recovery': {
      id: '/van-recovery'
      path: '/van-recovery'
      fullPath: '/van-recovery'
      preLoaderRoute: typeof VanRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-transport': {
      id: '/vehicle-transport'
      path: '/vehicle-transport'
      fullPath: '/vehicle-transport'
      preLoaderRoute: typeof VehicleTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-winching': {
      id: '/vehicle-winching'
      path: '/vehicle-winching'
      fullPath: '/vehicle-winching'
      preLoaderRoute: typeof VehicleWinchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrong-fuel-recovery': {
      id: '/wrong-fuel-recovery'
      path: '/wrong-fuel-recovery'
      fullPath: '/wrong-fuel-recovery'
      preLoaderRoute: typeof WrongFuelRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccidentRecoveryRoute: AccidentRecoveryRoute,
  AuctionVehicleCollectionRoute: AuctionVehicleCollectionRoute,
  BreakdownRecoveryRoute: BreakdownRecoveryRoute,
  CarRecoveryRoute: CarRecoveryRoute,
  CarTrailerRecoveryRoute: CarTrailerRecoveryRoute,
  ContactRoute: ContactRoute,
  EmergencyCarRecoveryRoute: EmergencyCarRecoveryRoute,
  FaqsRoute: FaqsRoute,
  FlatBatteryAssistanceRoute: FlatBatteryAssistanceRoute,
  FuelDeliveryRoute: FuelDeliveryRoute,
  GalleryRoute: GalleryRoute,
  JumpStartRoute: JumpStartRoute,
  LongDistanceVehicleTransportRoute: LongDistanceVehicleTransportRoute,
  LuxuryExoticCarTowingRoute: LuxuryExoticCarTowingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RecoveryToMechanicRoute: RecoveryToMechanicRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Suv4x4RecoveryRoute: Suv4x4RecoveryRoute,
  TermsRoute: TermsRoute,
  TradeVehicleDeliveryRoute: TradeVehicleDeliveryRoute,
  TrailerTransportRoute: TrailerTransportRoute,
  VanRecoveryRoute: VanRecoveryRoute,
  VehicleTransportRoute: VehicleTransportRoute,
  VehicleWinchingRoute: VehicleWinchingRoute,
  WrongFuelRecoveryRoute: WrongFuelRecoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
